"""added user type for user model

Revision ID: 01e8f3f57814
Revises: 895dc8932d77
Create Date: 2024-11-20 03:10:29.122637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01e8f3f57814'
down_revision: Union[str, None] = '895dc8932d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_type = postgresql.ENUM('CEO', 'EMPLOYEE', name='usertype', create_type=False)
    user_type.create(op.get_bind(), checkfirst=True)
    op.add_column('users',
                  sa.Column('user_type', user_type,
                            nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###
