"""added updated at for models

Revision ID: 3c994a40a68d
Revises: 13df48a5f247
Create Date: 2024-11-17 12:51:01.388153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c994a40a68d'
down_revision: Union[str, None] = '13df48a5f247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balconies', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('conditions', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('districts', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('floors', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('rooms', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('storeys', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('types', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('types', 'updated_at')
    op.drop_column('storeys', 'updated_at')
    op.drop_column('rooms', 'updated_at')
    op.drop_column('floors', 'updated_at')
    op.drop_column('districts', 'updated_at')
    op.drop_column('conditions', 'updated_at')
    op.drop_column('balconies', 'updated_at')
    # ### end Alembic commands ###
