"""added fixes for updated_at

Revision ID: 3cbd31aac8c5
Revises: 3c994a40a68d
Create Date: 2024-11-17 13:21:02.055565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cbd31aac8c5'
down_revision: Union[str, None] = '3c994a40a68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
