"""added floor_id to estate

Revision ID: 895dc8932d77
Revises: fbcdd99f44b4
Create Date: 2024-11-20 01:46:24.277286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895dc8932d77'
down_revision: Union[str, None] = 'fbcdd99f44b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estates', sa.Column('floor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'estates', 'floors', ['floor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estates', type_='foreignkey')
    op.drop_column('estates', 'floor_id')
    # ### end Alembic commands ###
