"""added fixes for estate

Revision ID: fbcdd99f44b4
Revises: 99e17bbaf4d6
Create Date: 2024-11-20 01:30:46.599929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbcdd99f44b4'
down_revision: Union[str, None] = '99e17bbaf4d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estates', sa.Column('manager_phone', sa.String(), nullable=True))
    op.add_column('estates', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estates', 'notes')
    op.drop_column('estates', 'manager_phone')
    # ### end Alembic commands ###
